GET http://localhost:5098/todos

###
POST http://localhost:5098/todos
Content-Type: application/json

{
    "id": 2,
    "name": "Write another demo",
    "dueDate": "2024-12-31",
    "isCompleted": false
}

### 
GET http://localhost:5098/todos/2

###
DELETE http://localhost:5098/todos/2

###
POST http://localhost:5098/todos
Content-Type: application/json

{
    "id": 1,
    "name": "Write demo",
    "dueDate": "2024-12-31",
    "isCompleted": false
}

###
GET http://localhost:5098/tasks/2

